/**
 * TermCast - Exporter
 * 
 * Export recordings to various formats
 */

import * as fs from 'fs-extra';
import * as path from 'path';
import chalk from 'chalk';
import { Recording, ExportOptions, TerminalFrame } from './types';

export class TerminalExporter {
  private recording: Recording;

  constructor(recording: Recording) {
    this.recording = recording;
  }

  /**
   * Export recording to specified format
   */
  async export(options: ExportOptions): Promise<string> {
    const outputPath = options.output;

    switch (options.format) {
      case 'asciinema':
        return this.exportAsciinema(outputPath);
      case 'html':
        return this.exportHtml(outputPath, options);
      case 'markdown':
        return this.exportMarkdown(outputPath, options);
      case 'gif':
        return this.exportGif(outputPath, options);
      default:
        throw new Error(`Unsupported format: ${options.format}`);
    }
  }

  /**
   * Export to asciinema format
   */
  private async exportAsciinema(outputPath: string): Promise<string> {
    const header = JSON.stringify({
      version: 2,
      width: this.recording.header.width,
      height: this.recording.header.height,
      timestamp: new Date(this.recording.header.timestamp).getTime() / 1000,
      env: this.recording.header.env
    });

    const frames = this.recording.frames
      .map(f => JSON.stringify([f.time / 1000, 'o', Buffer.from(f.data, 'base64').toString()]))
      .join('\n');

    const content = header + '\n' + frames;
    await fs.writeFile(outputPath, content);

    console.log(chalk.green(`✅ Exported to asciinema: ${outputPath}`));
    return outputPath;
  }

  /**
   * Export to HTML
   */
  private async exportHtml(outputPath: string, options: ExportOptions): Promise<string> {
    const theme = options.theme || 'dark';
    const isDark = theme === 'dark';

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.recording.header.title || 'Terminal Recording'}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
      background: ${isDark ? '#1e1e1e' : '#ffffff'};
      color: ${isDark ? '#d4d4d4' : '#333333'};
      padding: 20px;
      line-height: 1.5;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
    }
    .header {
      margin-bottom: 20px;
      padding-bottom: 15px;
      border-bottom: 1px solid ${isDark ? '#333' : '#eee'};
    }
    .header h1 {
      font-size: 24px;
      margin-bottom: 10px;
    }
    .meta {
      color: ${isDark ? '#888' : '#666'};
      font-size: 14px;
    }
    .terminal {
      background: ${isDark ? '#0d0d0d' : '#f5f5f5'};
      border-radius: 8px;
      padding: 20px;
      overflow-x: auto;
      font-size: 14px;
      line-height: 1.6;
      box-shadow: 0 4px 20px rgba(0,0,0,0.3);
    }
    .terminal-header {
      display: flex;
      gap: 8px;
      margin-bottom: 15px;
      padding-bottom: 10px;
      border-bottom: 1px solid ${isDark ? '#333' : '#ddd'};
    }
    .terminal-btn {
      width: 12px;
      height: 12px;
      border-radius: 50%;
    }
    .btn-red { background: #ff5f56; }
    .btn-yellow { background: #ffbd2e; }
    .btn-green { background: #27ca40; }
    .content {
      white-space: pre-wrap;
      word-break: break-all;
    }
    .timestamp {
      color: ${isDark ? '#666' : '#999'};
      font-size: 12px;
    }
    .annotation {
      background: ${isDark ? '#2a2a2a' : '#fff3cd'};
      border-left: 3px solid ${isDark ? '#4a9eff' : '#ffc107'};
      padding: 10px;
      margin: 10px 0;
      font-size: 13px;
    }
    .footer {
      margin-top: 20px;
      padding-top: 15px;
      border-top: 1px solid ${isDark ? '#333' : '#eee'};
      text-align: center;
      color: ${isDark ? '#666' : '#999'};
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🎬 ${this.recording.header.title || 'Terminal Recording'}</h1>
      <div class="meta">
        Duration: ${this.recording.header.duration?.toFixed(2) || 'N/A'}s | 
        Frames: ${this.recording.frames.length} |
        Size: ${this.recording.header.width}x${this.recording.header.height}
      </div>
    </div>
    <div class="terminal">
      <div class="terminal-header">
        <div class="terminal-btn btn-red"></div>
        <div class="terminal-btn btn-yellow"></div>
        <div class="terminal-btn btn-green"></div>
      </div>
      <div class="content">${this.renderContent(options)}</div>
    </div>
    <div class="footer">
      Generated by <a href="https://github.com/gitstq/termcast" style="color: #4a9eff;">TermCast</a>
    </div>
  </div>
</body>
</html>`;

    await fs.writeFile(outputPath, html);
    console.log(chalk.green(`✅ Exported to HTML: ${outputPath}`));
    return outputPath;
  }

  /**
   * Render terminal content for HTML
   */
  private renderContent(options: ExportOptions): string {
    let content = '';
    
    for (const frame of this.recording.frames) {
      const data = Buffer.from(frame.data, 'base64').toString();
      // Escape HTML
      const escaped = data
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
      content += escaped;
    }

    // Redact sensitive data if requested
    if (options.redactSensitive) {
      content = this.redactSensitive(content);
    }

    return content;
  }

  /**
   * Export to Markdown
   */
  private async exportMarkdown(outputPath: string, options: ExportOptions): Promise<string> {
    const md = `# 🎬 ${this.recording.header.title || 'Terminal Recording'}

> Duration: ${this.recording.header.duration?.toFixed(2) || 'N/A'}s | Frames: ${this.recording.frames.length}

## Terminal Session

\`\`\`bash
${this.extractCommands(options)}
\`\`\`

## Recording Details

| Property | Value |
|----------|-------|
| Duration | ${this.recording.header.duration?.toFixed(2) || 'N/A'}s |
| Frames | ${this.recording.frames.length} |
| Size | ${this.recording.header.width}x${this.recording.header.height} |
| Shell | ${this.recording.header.shell || 'N/A'} |
| Created | ${this.recording.header.timestamp} |

---

*Generated by [TermCast](https://github.com/gitstq/termcast)*
`;

    await fs.writeFile(outputPath, md);
    console.log(chalk.green(`✅ Exported to Markdown: ${outputPath}`));
    return outputPath;
  }

  /**
   * Extract commands from recording
   */
  private extractCommands(options: ExportOptions): string {
    let content = '';
    
    for (const frame of this.recording.frames) {
      const data = Buffer.from(frame.data, 'base64').toString();
      content += data;
    }

    // Strip ANSI codes
    content = content.replace(/\x1b\[[0-9;]*m/g, '');
    
    // Redact sensitive data if requested
    if (options.redactSensitive) {
      content = this.redactSensitive(content);
    }

    return content;
  }

  /**
   * Export to GIF (requires external tool)
   */
  private async exportGif(outputPath: string, options: ExportOptions): Promise<string> {
    // Note: This would require asciinema agg or similar tool
    // For now, we'll create a placeholder
    const placeholder = `# GIF Export

To export to GIF, please install asciinema's agg tool:

\`\`\`bash
pip install agg
\`\`\`

Then run:

\`\`\`bash
agg ${outputPath.replace('.gif', '.cast')} ${outputPath}
\`\`\`

Alternatively, use the HTML export and capture with a screen recording tool.
`;

    await fs.writeFile(outputPath.replace('.gif', '-gif-instructions.md'), placeholder);
    console.log(chalk.yellow(`⚠️  GIF export requires external tool. Instructions saved.`));
    return outputPath;
  }

  /**
   * Redact sensitive information
   */
  private redactSensitive(content: string): string {
    // Redact API keys
    content = content.replace(/[A-Za-z0-9]{32,}/g, '[REDACTED]');
    // Redact passwords
    content = content.replace(/password[=:]\s*\S+/gi, 'password=[REDACTED]');
    // Redact tokens
    content = content.replace(/token[=:]\s*\S+/gi, 'token=[REDACTED]');
    // Redact secrets
    content = content.replace(/secret[=:]\s*\S+/gi, 'secret=[REDACTED]');
    
    return content;
  }
}

/**
 * Quick export function
 */
export async function quickExport(
  recording: Recording, 
  format: ExportOptions['format'], 
  output: string
): Promise<string> {
  const exporter = new TerminalExporter(recording);
  return exporter.export({ format, output });
}
